import { useCallback } from 'react';
import { FileDown } from 'lucide-react';
import { useStore } from '@/stores';
import { generateInsights } from '@/analytics';
import { INTERNATIONAL_DENSITY_STANDARD } from '@/domain';

export function ExportSummary() {
  const scenario = useStore((s) => s.scenario);
  const visitors = useStore((s) => s.visitors);
  const zones = useStore((s) => s.zones);
  const media = useStore((s) => s.media);
  const timeState = useStore((s) => s.timeState);
  const latestSnapshot = useStore((s) => s.latestSnapshot);

  const handleExportText = useCallback(() => {
    if (!scenario || !latestSnapshot) return;

    const active = visitors.filter((v) => v.isActive);
    const exited = visitors.filter((v) => !v.isActive);
    const minutes = Math.floor(timeState.elapsed / 60000);
    const seconds = Math.floor((timeState.elapsed % 60000) / 1000);
    const mediaStats = useStore.getState().mediaStats;
    const groups = useStore.getState().groups;
    const insights = generateInsights(latestSnapshot, zones, media, mediaStats, visitors, groups);

    let report = '';
    report += '═══════════════════════════════════════════════════\n';
    report += '  AION mark01 — Exhibition Simulation Report\n';
    report += '  Generated by ABOARD INTERACTIVE\n';
    report += '═══════════════════════════════════════════════════\n\n';

    report += `Scenario: ${scenario.meta.name} (v${scenario.meta.version})\n`;
    report += `Duration: ${minutes}m ${seconds}s\n`;
    report += `Date: ${new Date().toLocaleString()}\n\n`;

    report += '── SUMMARY ────────────────────────────────────────\n';
    report += `Total Visitors Spawned : ${visitors.length}\n`;
    report += `Currently Active       : ${active.length}\n`;
    report += `Exited                 : ${exited.length}\n`;
    report += `Avg Fatigue            : ${Math.round(latestSnapshot.fatigueDistribution.mean * 100)}%\n`;
    report += `Peak Congestion        : ${Math.round(Math.max(...latestSnapshot.zoneUtilizations.map((u) => u.ratio)) * 100)}%\n`;
    report += `Bottleneck Count       : ${latestSnapshot.bottlenecks.filter((b) => b.score > 0.5).length}\n\n`;

    report += '── ZONE UTILIZATION ───────────────────────────────\n';
    for (const u of latestSnapshot.zoneUtilizations) {
      const zone = zones.find((z) => z.id === u.zoneId);
      if (!zone) continue;
      const pct = Math.round(u.ratio * 100);
      const areaPerPerson = u.currentOccupancy > 0 ? zone.area / u.currentOccupancy : zone.area;
      const meetsStd = areaPerPerson >= INTERNATIONAL_DENSITY_STANDARD;
      const bar = '█'.repeat(Math.min(20, Math.round(pct / 5))) + '░'.repeat(Math.max(0, 20 - Math.round(pct / 5)));
      report += `  ${zone.name.padEnd(20)} [${bar}] ${String(u.currentOccupancy).padStart(3)}/${zone.capacity} (${pct}%) ${meetsStd ? '✓' : '✗ DENSITY'}\n`;
    }
    report += '\n';

    report += '── INSIGHTS ───────────────────────────────────────\n';
    if (insights.length === 0) {
      report += '  No critical issues detected.\n';
    }
    for (const ins of insights) {
      const icon = ins.severity === 'critical' ? '🔴' : ins.severity === 'warning' ? '🟡' : 'ℹ️';
      report += `  ${icon} [${ins.category.toUpperCase()}] ${ins.problem}\n`;
      report += `     Cause: ${ins.cause}\n`;
      report += `     Action: ${ins.recommendation}\n\n`;
    }

    report += '── MEDIA PERFORMANCE ──────────────────────────────\n';
    for (const m of media) {
      const zone = zones.find((z) => z.id === m.zoneId);
      report += `  ${m.type.replace(/_/g, ' ').padEnd(22)} in ${(zone?.name ?? '?').padEnd(18)} cap:${m.capacity}\n`;
    }
    report += '\n';

    report += '═══════════════════════════════════════════════════\n';
    report += '  Report generated by AION mark01\n';
    report += '  ABOARD INTERACTIVE © 2026\n';
    report += '═══════════════════════════════════════════════════\n';

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aion-report-${scenario.meta.name.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [scenario, visitors, zones, media, timeState, latestSnapshot]);

  if (!latestSnapshot || !scenario) return null;

  return (
    <button
      onClick={handleExportText}
      className="w-full flex items-center justify-center gap-1.5 px-3 py-2 text-[10px] font-medium rounded-xl bg-secondary text-secondary-foreground hover:bg-accent transition-colors"
    >
      <FileDown className="w-3.5 h-3.5" /> Export Text Report
    </button>
  );
}
